### PR TITLE
docs: update taint names `master`=>`control-plane`

### PR DESCRIPTION
**Pull request by hxtmdev**
https://github.com/kubernetes/enhancements/blob/35befff0ad33187b2c93141d5fe1513a1b4a39a1/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md#summary

### CODE REVIEW

**Comment by frezbo** [comment]
These are older version of talos shipped with K8s that did not have the name change, so not relevant.

**Comment by hxtmdev** [comment]
Are you sure it should stay at the old name? I just set up a fresh cluster with sidero and had to use the new one as I was installing a current version of K8s.

Also it says `Version v0.6 of the documentation is for the Sidero Metal version being developed.`.

**Comment by frezbo** [comment]
>  Also it says Version v0.6 of the documentation is for the Sidero Metal version being developed..

Sidero Uses different docs than Talos https://github.com/siderolabs/sidero/tree/main/website

**Comment by hxtmdev** [comment]
I missed that the guide as a whole is targeting K8s 1.22.2, my bad. Thanks for the quick replies.

**Pull request closed without merging**
