### PR TITLE
feat: allow configuring Sidero deployment strategy

### PR DESCRIPTION
**Pull request by lion7**
Upgrading Sidero on a single-node cluster with host networking enabled fails because the used ports can only be bound once. By setting the deployment strategy to `Recreate` in these cases upgrades can succeed (but with a small amount of downtime).

Signed-off-by: Gerard de Leeuw <gdeleeuw@leeuwit.nl>

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by lion7** [comment]
The sfyra build fails with `Error: failed to get provider components for the "talos" provider: target namespace can't be defaulted. Please specify a target namespace`, which is caused by the GitHub rename.
Maybe add a clusterctl.yaml to the CI build? Or just wait for upstream to merge https://github.com/kubernetes-sigs/cluster-api/pull/6328

**Review by smira — COMMENTED** [review]
:heart: thank you!

**Pull request merged**
