### PR TITLE
docs: move docs to hugo

### PR DESCRIPTION
**Pull request by rsmitty**
This PR moves our docs to match what's in Talos

Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

### CODE REVIEW

**Comment by rsmitty** [comment]
preview can be found here https://deploy-preview-802--wonderful-swartz-a1308c.netlify.app/

**Comment by smira** [comment]
there's no `Documentation` link in the navbar, I guess `menu: main` is missing in the latest `_index.md` file

**Comment by smira** [comment]
and I don't see @frezbo changes for copy to the clipboard

**Comment by rsmitty** [comment]
ah shoot, good catches. will fix and re-ping.

**Review by smira — APPROVED** [review]

**Comment by frezbo** [comment]
just a note to fix https://deploy-preview-802--wonderful-swartz-a1308c.netlify.app/v0.5/getting-started/prereq-dhcp/ to use proper code tag for code blocks

**Review by frezbo — APPROVED** [review]

**Pull request merged**
